name: CoordBoard
version: 1.0
api-version: 1.20
main: fr.forky.coordboard.Main
commands:
  playerlist:
    description: List the connected players from custom player list class.
    usage: /<command>
    aliases: listp
  coord:
    description: Action on custom coordinates
    usage: /<command> <get|add|list|delete|go|favorite|unfavorite|stop> [name]
    aliases: [c, cb, coordboard]