name: CoordBoard
version: 1.0
api-version: 1.19
main: fr.forky.coordboard.Main
commands:
  playerlist:
    description: List the connected players from custom player list class.
    usage: /<command>
    aliases: listp