name: CoordBoard
version: 1.0
api-version: '26.1'
main: fr.forky.coordboard.Main
commands:
  playerlist:
    description: List the connected players from custom player list class.
    usage: /<command>
    aliases: listp
  coord:
    description: Gestion des coordonnées
    usage: /<command> <add|get|list|delete|rename|favorite|unfavorite|go|stop|share|help> [args]
    aliases: [c, cb, coordboard]